- type: job
  id: Captain
  name: job-name-captain
  description: job-description-captain
  playTimeTracker: JobCaptain
  requirements:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 54000 # 15 hours, imp
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 54000 # 15 hours, imp
    - !type:DepartmentTimeRequirement
      department: Security
      time: 54000 # 15 hours
    - !type:DepartmentTimeRequirement #imp
      department: Cargo
      time: 54000 # 15 hours
    - !type:DepartmentTimeRequirement #imp
      department: Science
      time: 54000 # 15 hours
    - !type:DepartmentTimeRequirement
      department: Command
      time: 72000 # 20 hours, imp
  weight: 20
  startingGear: CaptainGear
  icon: "JobIconCaptain"
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: CaptainGear
  equipment:
    #shoes: ClothingShoesBootsLaceup #imp
    #eyes: ClothingEyesGlassesCommand #imp
    #gloves: ClothingHandsGlovesCaptain #imp
    id: CaptainPDA
    #ears: ClothingHeadsetAltCommand #imp
  storage:
    back:
    - Flash
    # - StationCharter

- type: chameleonOutfit
  id: CaptainChameleonOutfit
  job: Captain
  hasMindShield: true
  equipment:
    head: ClothingHeadHatCapcap
    eyes: ClothingEyesGlassesCommand
    mask: ClothingMaskGasCaptain
    neck: ClothingNeckCloakCap
