- type: randomHumanoidSettings
  id: VisitorBrigmedic
  parent: VisitorSecurity
  components:
    - type: GhostRole
      name: job-name-brigmedic
      requirements:
        - !type:DepartmentTimeRequirement
          department: Security
          time: 36000 #10 hrs
        - !type:DepartmentTimeRequirement
          department: Medical
          time: 14400 #4 hrs
    - type: Loadout
      prototypes: [ VisitorBrigmedic, VisitorBrigmedicAlt ]
      roleLoadout: [ RoleSurvivalSecurity ]

- type: randomHumanoidSettings
  id: VisitorCourier
  parent: VisitorCargonian
  components:
    - type: GhostRole
      name: job-name-courier
    - type: Loadout
      prototypes: [ VisitorCourier, VisitorCourierAlt ]
      roleLoadout: [ RoleSurvivalStandard ]

- type: randomHumanoidSettings
  id: VisitorRoboticist
  parent: VisitorScience
  components:
    - type: GhostRole
      name: job-name-roboticist
    - type: Loadout
      prototypes: [ VisitorRoboticist, VisitorRoboticistAlt ]
      roleLoadout: [ RoleSurvivalStandard ]

- type: randomHumanoidSettings
  id: VisitorAdminAssistant
  parent: VisitorHead
  components:
    - type: GhostRole
      name: job-name-admin-assistant
    - type: Loadout
      prototypes: [ VisitorAdminAssistant, VisitorAdminAssistantAlt ]
      roleLoadout: [ RoleSurvivalStandard ]

- type: randomHumanoidSettings
  id: VisitorHospitalityDirector
  parent: VisitorHead
  components:
    - type: GhostRole
      name: job-name-hd
      requirements:
        - !type:DepartmentTimeRequirement
          department: Service
          time: 18000 #5 hrs
        - !type:OverallPlaytimeRequirement
          time: 36000 #10 hrs
    - type: Loadout
      prototypes: [ VisitorHospitalityDirector, VisitorHospitalityDirectorAlt ]
      roleLoadout: [ RoleSurvivalStandard ]

- type: randomHumanoidSettings
  id: VisitorLibrarianCryptid
  parent: VisitorCivilian
  components:
    - type: GhostRole
      name: job-name-librarian
      rules: ghost-role-information-antagonistchance-rules
    - type: Loadout
      prototypes: [ VisitorLibrarian, VisitorLibrarianAlt ]
      roleLoadout: [ RoleSurvivalStandard ]
    - type: RandomAntagChance
      antagRole: Heretic
      fallbackRole: MindRoleGhostRoleNeutral
      chance: 0.3

# CentComm Interns
- type: randomHumanoidSettings
  id: CentcommIntern
  parent: EventHumanoidCentcomm
  components:
  - type: RandomHumanoidAppearance
    randomizeName: true
  - type: GhostRole
    name: Centcomm Intern
    description: job-description-centcomm-intern
    rules: ghost-role-information-nonantagonist-rules
    raffle:
      settings: short
    job: CentcommIntern
  - type: Loadout
    prototypes: [ CentcommInternGear ]
    roleLoadout: [ RoleSurvivalStandard ]

- type: randomHumanoidSettings
  id: CentcommInternLeader
  parent: EventHumanoidCentcomm
  components:
  - type: RandomHumanoidAppearance
    randomizeName: true
  - type: GhostRole
    name: CentComm Head Intern
    description: job-description-centcomm-intern-leader
    rules: ghost-role-information-nonantagonist-rules
    raffle:
      settings: short
    job: CentcommInternLeader
  - type: Loadout
    prototypes: [ CentcommInternLeaderGear ]
    roleLoadout: [ RoleSurvivalStandard ]

- type: randomHumanoidSettings
  id: CentcommInternUnarmed
  parent: EventHumanoidCentcomm
  components:
  - type: RandomHumanoidAppearance
    randomizeName: true
  - type: GhostRole
    name: Centcomm Intern
    description: job-description-centcomm-intern-unarmed
    rules: ghost-role-information-nonantagonist-rules
    raffle:
      settings: short
    job: CentcommIntern
  - type: Loadout
    prototypes: [ CentcommInternUnarmedGear ]
    roleLoadout: [ RoleSurvivalStandard ]

- type: randomHumanoidSettings
  id: CentcommInternLeaderUnarmed
  parent: EventHumanoidCentcomm
  components:
  - type: RandomHumanoidAppearance
    randomizeName: true
  - type: GhostRole
    name: CentComm Head Intern
    description: job-description-centcomm-intern-leader-unarmed
    rules: ghost-role-information-nonantagonist-rules
    raffle:
      settings: short
    job: CentcommInternLeader
  - type: Loadout
    prototypes: [ CentcommInternLeaderUnarmedGear ]
    roleLoadout: [ RoleSurvivalStandard ]
