- type: job
  id: HeadOfSecurity
  name: job-name-hos
  description: job-description-hos
  playTimeTracker: JobHeadOfSecurity
  requirements:
    - !type:RoleTimeRequirement
      role: JobWarden
      time: 3h # imp, was 1h
    - !type:RoleTimeRequirement
      role: JobDetective
      time: 1h # knowing how to use the tools is important
    - !type:RoleTimeRequirement
      role: JobSecurityOfficer
      time: 10h # imp, was 5h
    - !type:DepartmentTimeRequirement
      department: Security
      time: 90h # imp, was 10h
    - !type:OverallPlaytimeRequirement # imp add
      time: 40h
  weight: 10
  startingGear: HoSGear
  icon: "JobIconHeadOfSecurity"
  supervisors: job-supervisors-hop-captain #imp
  canBeAntag: false
  access:
  - HeadOfSecurity
  - Command
  - Brig
  - Security
  - Armory
  - Maintenance
  #- Service imp edit
  - External
  - Detective
  - Cryogenics
  - Vault #imp
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: HoSGear
  equipment:
    # eyes: ClothingEyesGlassesSecurity imp loadouts
    id: HoSPDA
    gloves: ClothingHandsGlovesCombat
    # pocket1: WeaponPistolMk58 imp loadouts
  storage:
    back:
    - Flash
    # - MagazinePistol imp loadouts


- type: chameleonOutfit
  id: HeadOfSecurityChameleonOutfit
  job: HeadOfSecurity
  hasMindShield: true
  equipment:
    mask: ClothingMaskGasSecurity
    neck: ClothingNeckCloakHos
