- type: antag
  id: Recruiter
  name: roles-antag-syndicate-recruiter-name
  objective: roles-antag-syndicate-recruiter-objective
  antagonist: false # you ask questions and write papers not kill people
  playTimeTracker: AntagSyndicateRecruiter

- type: startingGear
  id: SyndicateRecruiterGear
  equipment:
    jumpsuit: ClothingUniformCybersunAttorney
    back: ClothingBackpackSatchel
    head: ClothingHeadHatFedoraBrown
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesColorWhite
    outerClothing: ClothingOuterCybersunOvercoat
    shoes: ClothingShoesLeather
    id: UndercoverPDA
    ears: ClothingHeadsetGrey
    pocket1: PenRecruiter
    pocket2: RubberStampSyndicate
  inhand:
    - RecruiterBriefcase
