# THIS FILE IS BEING IGNORED
# TO ADD MAPS TO THIS POOL, GO TO Prototypes/_Impstation/Maps/Pools/default.yml INSTEAD
- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Amber
  - Bagel
  - Box
  - Elkridge
  - Fland
  - Marathon
  - Oasis
  - Packed
  - Plasma
  - Reach
  - Exo
