- type: job
  id: Psychologist
  name: job-name-psychologist
  description: job-description-psychologist
  playTimeTracker: JobPsychologist
  startingGear: PsychologistGear
  icon: "JobIconPsychologist"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  extendedAccess:
  - Chemistry
  special: # imp
  - !type:AddComponentSpecial
    components:
    - type: SupermatterSoother

- type: startingGear
  id: PsychologistGear
  equipment:
    id: PsychologistPDA
    ears: ClothingHeadsetMedical
    belt: ClothingBeltPaperworkFilled # imp
  storage:
    back:
    - RubberStampPsychologist
    - PillCanisterPsych # imp

- type: chameleonOutfit
  id: PsychologistChameleonOutfit
  job: Psychologist
  equipment:
    head: ClothingHeadHatBeretMedic
    eyes: ClothingEyesHudMedical
    mask: ClothingMaskSterile
    outerClothing: ClothingOuterCoatLab
    neck: ClothingNeckStethoscope
    belt: ClothingBeltMedical
    gloves: ClothingHandsGlovesLatex
