- type: job
  id: CargoTechnician
  name: job-name-cargotech
  description: job-description-cargotech
  playTimeTracker: JobCargoTechnician
  # Begin DeltaV modifications - Add time requirement to cargo tech
  requirements:
  - !type:DepartmentTimeRequirement
    department: Cargo
    time: 21600 # 6 hrs ~3 shifts.
  # End DeltaV modifications
  startingGear: CargoTechGear
  icon: "JobIconCargoTechnician"
  supervisors: job-supervisors-qm
  access:
  - Cargo
  - Maintenance
  - Logistics #Imp
  extendedAccess:
  - Salvage
  - Courier # Imp

- type: startingGear
  id: CargoTechGear
  equipment:
    ears: ClothingHeadsetCargo
    pocket1: AppraisalTool
  #storage:
    #back:
    #- Stuff
