# For mantles
- type: loadoutEffectGroup
  id: MasterHoS
  effects:
  - !type:JobRequirementLoadoutEffect
    requirement:
      !type:RoleTimeRequirement
      role: JobHeadOfSecurity
      time: 36000 # Imp, 10 hrs

# Jumpsuit
- type: loadout
  id: HeadofSecurityJumpsuit
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoS

- type: loadout
  id: HeadofSecurityJumpskirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtHoS

- type: loadout
  id: HeadofSecurityTurtleneck
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoSAlt

- type: loadout
  id: HeadofSecurityTurtleneckSkirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtHoSAlt

- type: loadout
  id: HeadofSecurityProfessionalJumpsuit
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoSPro

- type: loadout
  id: HeadofSecurityProfessionalJumpskirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtHoSPro

- type: loadout
  id: HeadofSecurityFormalSuit
  equipment:
    jumpsuit: ClothingUniformJumpsuitHosFormal

- type: loadout
  id: HeadofSecurityFormalSkirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtHosFormal

# Head
- type: loadout
  id: HeadofSecurityHead
  equipment:
    head: ClothingHeadHatHoshat

- type: loadout
  id: HeadofSecurityBeret
  equipment:
    head: ClothingHeadHatBeretHoS

- type: loadout
  id: HeadofSecurityPatrolCap
  equipment:
    head: ClothingHeadHatHOSsoft

# Neck
- type: loadout
  id: HeadofSecurityCloak
  equipment:
    neck: ClothingNeckCloakHos

- type: loadout
  id: HeadofSecurityMantle
  equipment:
    neck: ClothingNeckMantleHOS
  effects:
  - !type:GroupLoadoutEffect
    proto: MasterHoS

- type: startingGear
  id: HeadofSecurityMantle
  equipment:
    neck: ClothingNeckMantleHOS

# OuterClothing
- type: loadout
  id: HeadofSecurityCoat
  equipment:
    outerClothing: ClothingOuterCoatHoSTrench

- type: loadout
  id: HeadofSecurityWinterCoat
  equipment:
    outerClothing: ClothingOuterWinterHoS

- type: loadout
  id: HeadofSecurityWinterCoatUnarmored
  equipment:
    outerClothing: ClothingOuterWinterHoSUnarmored

# Headset
- type: loadout
  id: HeadofSecurityHeadsetBasic
  equipment:
    ears: ClothingHeadsetHOS

- type: loadout
  id: HeadofSecurityHeadset
  equipment:
    ears: ClothingHeadsetAltSecurity

# Belt
- type: loadout
  id: HeadofSecurityShoulderHolster
  equipment:
    belt: ClothingBeltHolsterHOSFilled
