- type: startingGear
  id: MobCargorillaGear
  equipment:
    ears: ClothingHeadsetCargo
    id: CargorillaIDCard

- type: startingGear
  id: GoblinRobeOSP
  equipment:
    outerClothing: ClothingOuterCoatRobesGoblin
    belt: ClothingBeltUtilityGoblinRandomFill

- type: startingGear
  id: GoblinOSPEVA
  equipment:
    outerClothing: ClothingOuterGoblinEVASuit
    belt: ClothingBeltUtilityGoblinRandomFill
    back: ClothingBackpackSatchelLeather
    suitstorage: OxygenTankFilled
  storage:
    back:
    - ClothingOuterCoatRobesGoblin

- type: startingGear
  id: GoblinKnightArmor
  equipment:
    outerClothing: ClothingOuterGoblinKnightArmor
    back: ClothingBackpackSatchelLeather
  inhand:
    - GoblinClaymore
    - WoodenBuckler
