- type: entity
  id: CrateServiceSpaceCleaner
  parent: CratePlastic
  name: space cleaner refill crate
  description: Contains 6 jugs of space cleaner. Careful not to spill!
  components:
  - type: StorageFill
    contents:
      - id: JugSpaceCleaner
        amount: 6 #1200u total, ~half the amount

- type: entity
  id: CrateServiceJanitorialHardsuit
  parent: CrateTrashCartJani
  name: janitorial hardsuit crate
  description: A necessity for any janitor trying to keep the outside of the station as spotless as the inside.
  components:
  - type: StorageFill
    contents:
      - id: ClothingOuterHardsuitJanitor
        amount: 1

- type: entity
  id: CrateServiceMaintBarKit
  parent: CratePlastic
  name: maintenance bar kit
  description: A crate to carry on the tradition of bar engineering. Drinks not included.
  components:
    - type: StorageFill
      contents:
        - id: BoozeDispenserMachineCircuitboard
        - id: SodaDispenserMachineCircuitboard
        - id: MaterialWoodPlank
        - id: MaterialCloth10
        - id: DrinkGlass
          amount: 5
        - id: Spoon
        - id: DrinkShaker
        - id: CustomDrinkJug
          amount: 2
