# Goob content merge to bring it into line with the new system - impstation addition
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleChangeling
  name: Changeling Role
#  description: mind-role-changeling-description
  components:
  - type: MindRole
    antagPrototype: Changeling
    exclusiveAntag: true
    roleType: SoloAntagonist # imp edit
    primaryCurrency: EvolutionPoint #imp edit
  - type: ChangelingRole

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleHeretic
  name: Heretic Role
#  description: mind-role-changeling-description
  components:
  - type: MindRole
    antagPrototype: Heretic
    exclusiveAntag: true
    roleType: SoloAntagonist # imp edit
    primaryCurrency: KnowledgePoint #imp edit
  - type: HereticRole
