# When adding new food also add to random spawner located in Resources\Prototypes\Entities\Markers\Spawners\Random\Food_Drinks\food_produce.yml

- type: entity
  name: lemo fruit
  parent: FoodProduceBase
  id: FoodLemo
  description: A recently-discovered delicacy from the remote planet Teo.
  components:
  - type: FlavorProfile
    flavors:
      - sweet
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 14
        reagents:
        - ReagentId: Nutriment
          Quantity: 10
        - ReagentId: Vitamin
          Quantity: 4
  - type: Sprite
    sprite: Objects/Specific/Hydroponics/lemo.rsi
    state: fruit_pink
  - type: Produce
    seedId: lemo
  - type: SliceableFood
    count: 5
    slice: FoodLemoSlice
  - type: Tag
    tags:
    - Fruit
    - Lemo

- type: entity
  name: lemo slice
  parent: ProduceSliceBase
  id: FoodLemoSlice
  description: It takes 35 days to go off.
  components:
  - type: FlavorProfile
    flavors:
      - sweet
  - type: Sprite
    sprite: Objects/Specific/Hydroponics/lemo.rsi
  - type: Tag
    tags:
    - Fruit
    - Slice

