- type: job
  id: Courier
  name: job-name-courier
  description: job-description-courier
  playTimeTracker: JobCourier
  icon: JobIconCourier
  startingGear: CourierGear
  supervisors: job-supervisors-qm
  access:
  - Cargo
  - Courier
  - Maintenance

- type: startingGear
  id: CourierGear
  equipment:
    id: CourierPDA
    ears: ClothingHeadsetCargo
    belt: MailBag
    pocket1: HoloBellProjector

