- type: job
  id: Courier
  name: job-name-courier
  description: job-description-courier
  playTimeTracker: JobCourier
  icon: JobIconCourier
  startingGear: CourierGear
  supervisors: job-supervisors-qm
  access:
  - Cargo
  - Courier
  - Maintenance
  extendedAccess:
  - Logistics
  - Salvage
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
        - Courier
        - NanoTrasen

- type: startingGear
  id: CourierGear
  equipment:
    ears: ClothingHeadsetCargo
    belt: MailBag
    pocket1: HoloBellProjector

- type: chameleonOutfit
  id: CourierChameleonOutfit
  job: Courier
  equipment:
    head: ClothingHeadHatCouriersoft
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskBreath
    outerClothing: ClothingOuterWinterCourier
    neck: ClothingNeckScarfStripedBlue
    gloves: ClothingHandsGlovesFingerless
