- type: job
  id: Lawyer
  name: job-name-lawyer
  description: job-description-lawyer
  playTimeTracker: JobLawyer
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 36000 # 10 hrs, imp
    #imp edit start, substitute secoff playtime with sec playtime, better match upstream intent
    #- !type:RoleTimeRequirement
    #  role: JobSecurityOfficer
    #  time: 7200 #2 hrs
    - !type:DepartmentTimeRequirement
      department: Security
      time: 18000 #5 hrs
    #imp edit end,
  startingGear: LawyerGear
  icon: "JobIconLawyer"
  supervisors: job-supervisors-hop
  access:
  # - Service imp
  - Lawyer
  - Brig
  - Maintenance

- type: startingGear
  id: LawyerGear
  equipment:
#    id: LawyerPDA # imp, PDAs moved to loadout
    ears: ClothingHeadsetLawyer # imp edit
#  inhand: # imp, briefcases moved to loadout
#    - BriefcaseBrownFilled
  storage:
    back:
    - RubberStampLawyer
    - BookSpaceLaw

- type: chameleonOutfit
  id: LawyerChameleonOutfit
  job: Lawyer
  equipment:
    head: ClothingHeadHatBowlerHat
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskBreath
    neck: ClothingNeckLawyerbadge
    outerClothing: ClothingOuterWinterColorBlack
    gloves: ClothingHandsGlovesColorBlack
