# Seclink
- type: entity
  name: token box
  parent: BoxCardboard
  id: BoxToken
  description: A box full of tokens meant to be used in the SecLink radio.
  components:
  - type: Storage
    grid:
    - 0,0,2,0
  - type: StorageFill
    contents:
    - id: BatonToken5
    - id: DisablerToken5
    - id: UtilityToken5
  - type: Sprite
    layers:
    - state: box_security
