- type: job
  id: Brigmedic
  name: job-name-brigmedic
  description: job-description-brigmedic
  playTimeTracker: JobBrigmedic
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 10h
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 4h
  startingGear: BrigmedicGear
  icon: JobIconBrigmedic
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Medical
  - Security
  - Brig
  - Maintenance
  - External
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: BrigmedicGear
  equipment:
    ears: ClothingHeadsetBrigmedic
    id: BrigmedicPDA
    belt: ClothingBeltMedicalEMTFilled

- type: chameleonOutfit
  id: BrigmedicChameleonOutfit
  job: Brigmedic
  equipment:
    head: ClothingHeadHatBeretBrigmedic
    mask: ClothingMaskGasSecurity
    neck: ClothingNeckScarfStripedLightBlue
    gloves: ClothingHandsGlovesNitrile
