- type: antag
  id: HeadRev
  name: roles-antag-rev-head-name
  antagonist: true
  playTimeTracker: AntagHeadRevolutionary # imp
  setPreference: true
  objective: roles-antag-rev-head-objective
  guides: [ Revolutionaries ]
  requirements:
  # imp edit to change playtime req
  # - !type:OverallPlaytimeRequirement
  #   time: 1h
  - !type:DepartmentTimeRequirement
    department: Security
    time: 10h
  - !type:DepartmentTimeRequirement
    department: Command
    time: 10h
  # end imp

- type: antag
  id: Rev
  name: roles-antag-rev-name
  antagonist: true
  playTimeTracker: AntagRevolutionary # imp
  setPreference: false
  objective: roles-antag-rev-objective
  guides: [ Revolutionaries ]

- type: startingGear
  id: HeadRevGear
  storage:
    back:
    - Flash
    - ClothingEyesGlassesSunglasses
    - BoxEncryptionKeyRevolution # imp
