- type: antag
  id: SubvertedSilicon
  name: roles-antag-subverted-silicon-name
  antagonist: true
  requirements:
  - !type:OverallPlaytimeRequirement # Imp
    time: 3600 # 1h
  playTimeTracker: AntagSubvertedSilicon # imp
  setPreference: false
  objective: roles-antag-subverted-silicon-objective
