- type: antag
  id: Thief
  name: roles-antag-thief-name
  antagonist: true
  playTimeTracker: AntagThief # imp
  setPreference: true
  objective: roles-antag-thief-objective
  guides: [ Thieves ]
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 3600 # 1h

- type: startingGear
  id: ThiefGear
  storage:
    back:
    - ThiefBeacon
    - SatchelThief
    - ThiefBusinessCard #imp
