[game]
hostname = "[EN][MRP] Impstation"
desc = "Unofficial server for fans of RTVS featuring custom content. Come and see him."
soft_max_players = 100
# seconds
# default 120
round_restart_time = 300
# default 150
lobbyduration = 600

[server]
# TODO
# rules_file = "ImpstationRuleset"
uptime_restart_minutes = 480

[chat]
# Message Of The Day
# motd = ""

[ic]
flavor_text = true
# allows for use of nonalphanumeric characters in names.
# immediately going off if people get stupid with it.
restricted_names = false

[interaction]
# defaults
# rate_limit_count = 5
# rate_limit_period = 0.5
# rate_limit_announce_admins_delay = 120
rate_limit_count = 20

[infolinks]
discord = "https://discord.gg/erthpinball"
github = "https://github.com/impstation/imp-station-14"
website = "https://impstation.gay"
# wiki = ""
bug_report = "https://github.com/impstation/imp-station-14/issues"
appeal = "https://impstation.gay/banappeal"

[looc]
# people abused the privilege, so off it goes
# enabled_dead = true

[shuttle]
# allows for early shuttle launch with approval of 3 heads
emergency_early_launch_allowed = true

[ghost]
# sets time before ghost role buttons enable, so people hopefully Actually Read
role_time = 10

[tips]
# this doesn't actually propagate to the client right now
login_dataset = "LoginTips"

[whitelist]
enabled = false
# we do have a whitelist in place, but as of 15 august 2025 the server is open again
# whitelist cutoff date: ~0:00CT 28 april 2025
