name: "Labels: PR"

on:
- pull_request_target

jobs:
  labeler:
    if: ${{ ! contains(fromJSON('["ImpstationBot", "github-actions"]'), github.actor) }} # imp edit
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5
